### ISSUE TITLE
Instructions for Reproduction

### ISSUE THREAD

**Issue by jc-ryan** [brian7685/Video-M2E2#1]
We appreciate your contribution on multi-modal IE a lot! Could you please provide some more details for reproducing your code in readme and a link of the whole video m2e2 dataset(which seems to be missed) ? 
Thanks a lot !

**Comment by brian7685** [comment]
Hi, 
We will release the code soon.
For the dataset, the video ID is included in `vid_annotation.json`.
We will release the features and metadata soon.

**Comment by sabyasachee** [comment]
We can find the videos on YouTube from the keys of the `vid_annotation.json` file.
However where can we find the co-referential text (if exists) for each event and argument?
The json file provides the temporal boundaries and the bounding box information, but not the video to text mapping?

**Comment by brian7685** [comment]
The coreference text event is labeled as `"Event_Coreference": 1, `if the visual event is coreference with the first sentence.

**Comment by rathodankitha** [comment]
please help me to get this file   /kiwi-data/users/shoya/AIDA/obj_det_features/m2e2_obj_detections_merged.json.json 
or else if this file is get generated , so please guide me to generate it .

and it will be helpful if anyone share args which should be send with an example

**Comment by brian7685** [comment]
Got it, will get back to you soon!

**Comment by rathodankitha** [comment]
can I please know till when you guzz can update the repo ?

**Comment by brian7685** [comment]
Hi, turned out the features that were stored on the server were moved to other places and we can't find them.
Here are some codes and instructions to extract the features.
Please refer to the Local Features:
https://github.com/shoyasaxa/AIDA_MILO/blob/main/README.md

Here is the code and model on Google Drive:
https://drive.google.com/file/d/1WItK2GY5e6ZraDx_ovASNHI_ccjtLIZU/view?usp=sharing

**Comment by rathodankitha** [comment]
Thank you so much for sharing this , this will be very helpful to me  for
my project.
